### ISSUE TITLE
Error while handling submit_sm_resp pdu for'SubmitSM' object has no attribute 'response'

### ISSUE THREAD

**Issue by ghalebssalah** [jookies/jasmin#1218]
Hi,

I'm using the latest deb package, and I find the following error on messages.log when sending a message through rest-api, default configurations are being used 

ERROR    215995 (<class 'AttributeError'>) while handling submit_sm_resp pdu for msgid:0c4068b9-9d9d-4ceb-8a4e-96ce4b051118: 'SubmitSM' object has no attribute 'response'

Anyone has any idea?

**Comment by LinuxlinkedBD** [comment]
Hello @ghalebssalah,

I was also facing the same problem on latest release but older release doesn't have this issue. 
You can try jasmin-sms-gateway=0.11.0

**Comment by lobbiaa** [comment]
same here. And I'm using SMPP

**Comment by lobbiaa** [comment]
I have same issue. I tried Ubuntu2004, and 2204, tried jasmin0.11.0 and jasmin0.11.1, tried LXC, and kvm, no luck.
Anyone know why?

**Comment by hirantha-k** [comment]
Facing the same issue and all DLRs are not processed correctly due to unknown MSG IDs

**Comment by majidshirazy** [comment]
pip will install version 0.11.2, I've used pip install jasmin==0.11.0 and everything is ok now.

**Comment by majidshirazy** [comment]
> Hi,
> 
> I'm using the latest deb package, and I find the following error on messages.log when sending a message through rest-api, default configurations are being used
> 
> ERROR 215995 (<class 'AttributeError'>) while handling submit_sm_resp pdu for msgid:0c4068b9-9d9d-4ceb-8a4e-96ce4b051118: 'SubmitSM' object has no attribute 'response'
> 
> Anyone has any idea?

pip will install version 0.11.2. this version seems buggy or not a released version.
After I installed version 0.11.0 everything is ok now.
you can try
`pip install jasmin==0.11.0`

**Comment by attie-argentum** [comment]
Reverting 6eb0f0cbcb4e4f3126b54005dc963b6247da6015 appears to fix the situation (at least for `jasmin==0.11.1`), and it may not be a complete fix... but it's got things moving for us.

**Comment by yunier850710** [comment]
here new code to fix the issue, backup listeners.py and create a new one with this code
path /opt/jasmin-sms-gateway/venv/lib/python3.10/site-packages/jasmin/managers/
after applied, restart jasmind service, check messages.log

[code.txt](https://github.com/user-attachments/files/21198733/code.txt)
